### ISSUE TITLE
Missing programs after installation.

### ISSUE THREAD

**Issue by G4ZJHG6LLN** [KD9YQK/digipi_plus#4]
No service or programs showing for Gridtracker, Xastir, JS8Spotter or Gpredict after installation.

Install script appears to have downloaded, compiled and installed these programs, and at the end of the script it shows them being added to the GUI and Homepage. 

What is the difference between the Homepage and the GUI menu?

Regards

Ian.

**Comment by KD9YQK** [comment]
New service created for Xastir.  Homepage is the menu in the web browser. GUI is the menu in VNC.  A help page was also added to explain the operation of new apps added.
